name: releases

on:
  push:
    tags:
      - v*

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: test leaf
        run: cargo test -p leaf

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: build leaf
        run: cargo build -p leaf --release

  build-cross:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - x86_64-pc-windows-gnu
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: install deps
        run: |
          sudo apt update && sudo apt install llvm-dev libclang-dev clang libssl-dev pkg-config protobuf-compiler make -y

      - name: install cross
        run: |
          cargo install cross

      - name: build
        run: |
          cross build --release -p leaf --target ${{ matrix.target }}

  feature-matrix:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        features:
          - default-ring
          - default-openssl
          - config-json
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: build leaf with ${{ matrix.features }}
        run: cargo build -p leaf --no-default-features --features ${{ matrix.features }}

  create-release:
    needs: [test, build, build-cross, feature-matrix]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: build docs
        run: cargo doc -p leaf --no-deps

      - name: zip docs
        run: |
          mv target/doc leaf-doc
          zip -r leaf-doc.zip leaf-doc

      - name: package crate
        run: cargo package -p leaf --allow-dirty

      - name: publish release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            leaf-doc.zip
            target/package/*.crate
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
